Daria
Kuba-TLA/movieO pull request #34
Opened 2023-09-25 19:42 UTC by DariaTrabsky

2023-09-27 01:47 UTC, Irina312 approved these changes

2023-10-01 16:12 UTC, tsgilde approved these changes

2023-10-06 16:36 UTC, Kuba-TLA requested changes
Please remove report.html file from your commit. We don't want that file in remote branch

2023-10-07 13:11 UTC, Kuba-TLA approved these changes

2023-10-07 13:12 UTC, merged